/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_TPM1CH0SRC_TPM1_CH0 0x00u /*!<@brief TPM1 channel 0 input capture source select: TPM1_CH0 signal */
#define SOPT5_UART0RXSRC_UART_RX 0x00u  /*!<@brief UART0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u  /*!<@brief UART0 transmit data source select: UART0_TX pin */

/*! @name PORTA2 (number 28), J1[4]/D1/UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTA1 (number 27), J1[2]/D0/UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTB8 (number 47), J9[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Left_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_Left_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Left_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Left_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Left_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Left_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTB9 (number 48), J9[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Right_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_Right_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Right_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Right_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Right_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Right_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB10 (number 49), J9[5]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Back_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_Back_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Back_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Back_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Back_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Back_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB11 (number 50), J9[7]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Front_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_Front_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Front_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Front_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Front_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Front_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTB3 (number 46), J10[8]/A3
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Xval_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Xval_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Xval_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTB2 (number 45), J10[6]/A2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Yval_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Yval_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Yval_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTB1 (number 44), J10[4]/A1
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Yservo_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Yservo_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Yservo_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTB0 (number 43), J10[2]/A0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Xservo_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Xservo_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Xservo_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTE5 (number 6), J9[15]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SysTickOut_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SysTickOut_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SysTickOut_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SysTickOut_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SysTickOut_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SysTickOut_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
