/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v8.0
processor: MKL25Z128xxx4
package_id: MKL25Z128VLK4
mcu_data: ksdk2_0
processor_version: 8.0.1
board: FRDM-KL25Z
pin_labels:
- {pin_num: '6', pin_signal: PTE5, label: 'J9[15]', identifier: SysTickOut}
- {pin_num: '43', pin_signal: ADC0_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0, label: 'J10[2]/A0', identifier: Xservo}
- {pin_num: '44', pin_signal: ADC0_SE9/TSI0_CH6/PTB1/I2C0_SDA/TPM1_CH1, label: 'J10[4]/A1', identifier: Yservo}
- {pin_num: '45', pin_signal: ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/TPM2_CH0, label: 'J10[6]/A2', identifier: Yval}
- {pin_num: '46', pin_signal: ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/TPM2_CH1, label: 'J10[8]/A3', identifier: Xval}
- {pin_num: '47', pin_signal: PTB8/EXTRG_IN, label: 'J9[1]', identifier: Left}
- {pin_num: '48', pin_signal: PTB9, label: 'J9[3]', identifier: Right}
- {pin_num: '49', pin_signal: PTB10/SPI1_PCS0, label: 'J9[5]', identifier: Back}
- {pin_num: '50', pin_signal: PTB11/SPI1_SCK, label: 'J9[7]', identifier: Front}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '28', peripheral: UART0, signal: TX, pin_signal: TSI0_CH3/PTA2/UART0_TX/TPM2_CH1}
  - {pin_num: '27', peripheral: UART0, signal: RX, pin_signal: TSI0_CH2/PTA1/UART0_RX/TPM2_CH0}
  - {pin_num: '13', peripheral: ADC0, signal: 'DP, 0', pin_signal: ADC0_DP0/ADC0_SE0/PTE20/TPM1_CH0/UART0_TX}
  - {pin_num: '47', peripheral: GPIOB, signal: 'GPIO, 8', pin_signal: PTB8/EXTRG_IN, direction: OUTPUT}
  - {pin_num: '48', peripheral: GPIOB, signal: 'GPIO, 9', pin_signal: PTB9, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '49', peripheral: GPIOB, signal: 'GPIO, 10', pin_signal: PTB10/SPI1_PCS0, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '50', peripheral: GPIOB, signal: 'GPIO, 11', pin_signal: PTB11/SPI1_SCK, direction: OUTPUT}
  - {pin_num: '46', peripheral: ADC0, signal: 'SE, 13', pin_signal: ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/TPM2_CH1}
  - {pin_num: '45', peripheral: ADC0, signal: 'SE, 12', pin_signal: ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/TPM2_CH0}
  - {pin_num: '44', peripheral: TPM1, signal: 'CH, 1', pin_signal: ADC0_SE9/TSI0_CH6/PTB1/I2C0_SDA/TPM1_CH1}
  - {pin_num: '43', peripheral: TPM1, signal: 'CH, 0', pin_signal: ADC0_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0}
  - {pin_num: '6', peripheral: GPIOE, signal: 'GPIO, 5', pin_signal: PTE5, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t Left_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB8 (pin 47)  */
    GPIO_PinInit(BOARD_INITPINS_Left_GPIO, BOARD_INITPINS_Left_PIN, &Left_config);

    gpio_pin_config_t Right_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB9 (pin 48)  */
    GPIO_PinInit(BOARD_INITPINS_Right_GPIO, BOARD_INITPINS_Right_PIN, &Right_config);

    gpio_pin_config_t Back_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB10 (pin 49)  */
    GPIO_PinInit(BOARD_INITPINS_Back_GPIO, BOARD_INITPINS_Back_PIN, &Back_config);

    gpio_pin_config_t Front_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB11 (pin 50)  */
    GPIO_PinInit(BOARD_INITPINS_Front_GPIO, BOARD_INITPINS_Front_PIN, &Front_config);

    gpio_pin_config_t SysTickOut_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE5 (pin 6)  */
    GPIO_PinInit(BOARD_INITPINS_SysTickOut_GPIO, BOARD_INITPINS_SysTickOut_PIN, &SysTickOut_config);

    /* PORTA1 (pin 27) is configured as UART0_RX */
    PORT_SetPinMux(BOARD_INITPINS_DEBUG_UART_RX_PORT, BOARD_INITPINS_DEBUG_UART_RX_PIN, kPORT_MuxAlt2);

    /* PORTA2 (pin 28) is configured as UART0_TX */
    PORT_SetPinMux(BOARD_INITPINS_DEBUG_UART_TX_PORT, BOARD_INITPINS_DEBUG_UART_TX_PIN, kPORT_MuxAlt2);

    /* PORTB0 (pin 43) is configured as TPM1_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_Xservo_PORT, BOARD_INITPINS_Xservo_PIN, kPORT_MuxAlt3);

    /* PORTB1 (pin 44) is configured as TPM1_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_Yservo_PORT, BOARD_INITPINS_Yservo_PIN, kPORT_MuxAlt3);

    /* PORTB10 (pin 49) is configured as PTB10 */
    PORT_SetPinMux(BOARD_INITPINS_Back_PORT, BOARD_INITPINS_Back_PIN, kPORT_MuxAsGpio);

    /* PORTB11 (pin 50) is configured as PTB11 */
    PORT_SetPinMux(BOARD_INITPINS_Front_PORT, BOARD_INITPINS_Front_PIN, kPORT_MuxAsGpio);

    /* PORTB2 (pin 45) is configured as ADC0_SE12 */
    PORT_SetPinMux(BOARD_INITPINS_Yval_PORT, BOARD_INITPINS_Yval_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTB3 (pin 46) is configured as ADC0_SE13 */
    PORT_SetPinMux(BOARD_INITPINS_Xval_PORT, BOARD_INITPINS_Xval_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTB8 (pin 47) is configured as PTB8 */
    PORT_SetPinMux(BOARD_INITPINS_Left_PORT, BOARD_INITPINS_Left_PIN, kPORT_MuxAsGpio);

    /* PORTB9 (pin 48) is configured as PTB9 */
    PORT_SetPinMux(BOARD_INITPINS_Right_PORT, BOARD_INITPINS_Right_PIN, kPORT_MuxAsGpio);

    /* PORTE20 (pin 13) is configured as ADC0_DP0 */
    PORT_SetPinMux(PORTE, 20U, kPORT_PinDisabledOrAnalog);

    /* PORTE5 (pin 6) is configured as PTE5 */
    PORT_SetPinMux(BOARD_INITPINS_SysTickOut_PORT, BOARD_INITPINS_SysTickOut_PIN, kPORT_MuxAsGpio);

    SIM->SOPT4 = ((SIM->SOPT4 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT4_TPM1CH0SRC_MASK)))

                  /* TPM1 channel 0 input capture source select: TPM1_CH0 signal. */
                  | SIM_SOPT4_TPM1CH0SRC(SOPT4_TPM1CH0SRC_TPM1_CH0));

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK | SIM_SOPT5_UART0RXSRC_MASK)))

                  /* UART0 transmit data source select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX)

                  /* UART0 receive data source select: UART0_RX pin. */
                  | SIM_SOPT5_UART0RXSRC(SOPT5_UART0RXSRC_UART_RX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
